# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundation',
            name='support_count',
            field=models.IntegerField(editable=False),
        ),
    ]
