# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('support', '0002_auto_20171104_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundation',
            name='support_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
