# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 17:00
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionImage', models.ImageField(upload_to='')),
                ('point', models.IntegerField(blank=True, null=True)),
                ('answer1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer1',
                                              to='main.Answer')),
                ('answer2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer2',
                                              to='main.Answer')),
                ('answer3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer3',
                                              to='main.Answer')),
                ('answer4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer4',
                                              to='main.Answer')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level',
                                               to='main.Category')),
            ],
        ),
    ]
