# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0002_auto_20171022_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ManyToManyField(to='main.Category'),
        ),
    ]
